sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t rehan/client ./client

script:
  - docker run -e CI=true rehan/client npm run test -- --coverage

after_success:
  - docker build -t rehan/multi-client ./client
  - docker build -t rehan/multi-server ./server
  - docker build -t rehan/multi-worker ./worker
  - docker build -t rehan/multi-nginx ./nginx

