sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t rehanslife/client ./client

script:
  - docker run -e CI=true rehanslife/client npm run test -- --coverage

after_success:
  - docker build -t rehanslife/multi-client ./client
  - docker build -t rehanslife/multi-server ./server
  - docker build -t rehanslife/multi-worker ./worker
  - docker build -t rehanslife/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push rehanslife/multi-client
  - docker push rehanslife/multi-server
  - docker push rehanslife/multi-worker
  - docker push rehanslife/mult-nginx