sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f ./client/Dockerfile.dev -t rehan/client ./client

script:
  - docker run -e CI=true rehan/client npm run test -- --coverage

after_success:
  - docker build -t rehan/multi-client ./client
  - docker build -t rehan/multi-server ./server
  - docker build -t rehan/multi-worker ./worker
  - docker build -t rehan/multi-nginx ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push rehan/multi-client
  - docker push rehan/multi-server
  - docker push rehan/multi-worker
  - docker push rehan/mult-nginx