sudo: required

services:
  - docker

before_install: 
  # Getting back the encrypted file from travis yaml
  - openssl aes-256-cbc -K $encrypted_1c0fb2e058e0_key -iv $encrypted_1c0fb2e058e0_iv -in multi-k8s-411607-db3de3ca2b02.json.enc -out multi-k8s-411607-db3de3ca2b02.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-411607-db3de3ca2b02.json
