version: '3'

services:
  # postgres:
  #   restart: always
  #   image: postgres
  #   environment:
  #     - POSTGRES_PASSWORD=postgres_password
  # redis-server:
  #   restart: always
  #   image: redis

  client:
    image: "rehanslife/multi-client"
    mem_limit: 128m
    hostname: client

  server:
    restart: always
    image: "rehanslife/multi-server"
    hostname: api
    mem_limit: 128m
    # environment:
    #   - REDIS_HOST=redis-server
    #   - REDIS_PORT=6379
    #   - PGUSER=postgres 
    #   - PGHOST=postgres
    #   - PGDATABASE=postgres
    #   - PGPASSWORD=postgres_password
    #   - PGPORT=5432
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  worker:
    restart: always
    image: "rehanslife/multi-worker"
    mem_limit: 128m
    # environment:
    #   - REDIS_HOST=redis-server
    #   - REDIS_PORT=6379
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    restart: always
    image: 'rehanslife/multi-nginx'
    ports:
      - '80:80'
    mem_limit: 128m
