version: '3'

services:
  postgres:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis-server:
    restart: always
    image: redis

  worker:
    restart: always
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379

  nginx:
    depends_on:
      - api
      - client
    build: 
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '8080:80'

  api:
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - PGUSER=postgres 
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  
  client:
    restart: always
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    environment:
      - WDS_SOCKET_PORT=0
