version: '3'

services:
  client:
    image: "rehanslife/multi-client"
    mem_limit: 128m
  server:
    image: "rehanslife/multi-server"
    hostname: api
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "rehanslife/multi-worker"
    mem_limit: 128m
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: 'rehanslife/multi-nginx'
    ports:
      - '80:80'
    mem_limit: 128m
