apiVersion: apps/v1
kind: Deployment
metadata:
  name: postges-deployment
spec:
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
      - name: postges
        image: postgres
        # env:
          # - name: 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5432
